CREATE TABLE ENDERECO
		(	CODIGO BIGINT PRIMARY KEY AUTO_INCREMENT,
			CIDADE VARCHAR(50) NOT NULL,
            		BAIRRO VARCHAR(50) NOT NULL,
            		LOGRADOURO VARCHAR(50) NOT NULL,
			UF VARCHAR(2) NOT NULL,
            		COMPLEMENTO VARCHAR(100),
		        NUMERO VARCHAR(14) NOT NULL,
		        CEP INT(8)        
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CARGO
		(	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
			DESCRICAO VARCHAR(50) NOT NULL,
            		SALARIO FLOAT NOT NULL
		) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PESSOA
	( 	CODIGO BIGINT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(100) NOT NULL,
		CPF_CNPJ VARCHAR(14) NOT NULL,
		EMAIL VARCHAR(100),
		TELEFONE BIGINT(14),
		CELULAR BIGINT(14),
		DATA_CADASTRO DATE,
		ATIVO BOOLEAN,
		TIPO VARCHAR(2),
		DATA_NASCIMENTO DATE,
		NOME_FANTASIA VARCHAR(50),
		DATA_ENTRADA DATE,
		DATA_SAIDA DATE,
		ID_CARGO INT,
		ID_ENDERECO BIGINT NOT NULL,
		LOGIN VARCHAR(50),
		SENHA VARCHAR(150),
		CONSTRAINT FK_PESSOA_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (CODIGO),
		CONSTRAINT FK_FUNCIONARIO_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGO (CODIGO)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE PERMISSAO 
	(CODIGO INT NOT NULL PRIMARY KEY, DESCRICAO VARCHAR(50) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USUARIO_PERMISSAO
	(CODIGO_USUARIO BIGINT NOT NULL, CODIGO_PERMISSAO INT NOT NULL,
		CONSTRAINT FK_USUARIO_PERMISSAO FOREIGN KEY (CODIGO_USUARIO) REFERENCES PESSOA (CODIGO),
        CONSTRAINT FK_PERMISSAO_USUARIO FOREIGN KEY (CODIGO_PERMISSAO) REFERENCES PERMISSAO (CODIGO)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CARGO(DESCRICAO, SALARIO) 
	VALUES
    ('DESENVOLVEDOR JÚNIOR', 180.89);

INSERT INTO ENDERECO(CIDADE, BAIRRO, LOGRADOURO, UF, COMPLEMENTO, NUMERO, CEP) 
	VALUES
    ('Igarapé', 'Cidade Nova', 'Carola', 'MG', 'Casa', 53, 32900000 );

INSERT INTO PESSOA (NOME, CPF_CNPJ, EMAIL, CELULAR, TIPO, DATA_ENTRADA, ID_CARGO, ID_ENDERECO) 
	VALUES
    ('Cristiano', '13086182636', 'kiki.crist@hotmail.com', 31999685370, 'F', '2017-03-01', 1, 1);
